# See https://hub.docker.com/_/mysql/

ARG MYSQL_RELEASE=8.4

FROM mysql:${MYSQL_RELEASE}
ARG MYSQL_RELEASE

ADD mysql-${MYSQL_RELEASE}.cnf /etc/mysql/conf.d/z99-docker.cnf
RUN chown mysql:mysql /etc/mysql/conf.d/z99-docker.cnf \
    && chmod 0644 /etc/mysql/conf.d/z99-docker.cnf
